import streamlit as st
import pickle
import re
import requests
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

# -------------------------------------------------------------
# 1. Page Configuration
# -------------------------------------------------------------
st.set_page_config(page_title="Live News AI Validator", page_icon="🕵️", layout="centered")

# -------------------------------------------------------------
# 2. Secure NLTK Downloads (Cloud Safe)
# -------------------------------------------------------------
@st.cache_resource
def download_nltk_data():
    """Downloads stopwords only once when the server boots to prevent FileExistsError."""
    try:
        nltk.data.find('corpora/stopwords')
    except LookupError:
        nltk.download('stopwords', quiet=True)

download_nltk_data()

# -------------------------------------------------------------
# 3. Load Machine Learning Artifacts
# -------------------------------------------------------------
@st.cache_resource
def load_assets():
    """Loads the pre-trained model and vectorizer generated by model_builder.py."""
    with open('model.pkl', 'rb') as f:
        model = pickle.load(f)
    with open('vectorizer.pkl', 'rb') as f:
        vectorizer = pickle.load(f)
    return model, vectorizer

model, vectorizer = load_assets()

# -------------------------------------------------------------
# 4. Text Processing Engine
# -------------------------------------------------------------
ps = PorterStemmer()

def clean_text(content):
    """Cleans live text using the exact same logic used during model training."""
    # Remove non-alphabetic characters
    content = re.sub('[^a-zA-Z]', " ", content)
    # Convert to lowercase and split into words
    content = content.lower().split()
    # Stem and remove stopwords
    stop_words = set(stopwords.words('english'))
    content = [ps.stem(word) for word in content if word not in stop_words]
    return " ".join(content)

# -------------------------------------------------------------
# 5. Live Data API Fetch
# -------------------------------------------------------------
def fetch_live_news(query, api_key):
    """Calls the NewsAPI to grab the single most recent article for a given topic."""
    url = f"https://newsapi.org/v2/everything?q={query}&apiKey={api_key}&language=en&sortBy=publishedAt&pageSize=1"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            if data.get('articles') and len(data['articles']) > 0:
                article = data['articles'][0]
                return article.get('title', ''), article.get('description', ''), article.get('url', '')
    except Exception as e:
        st.error(f"API Connection Error: {e}")
    return None, None, None

# -------------------------------------------------------------
# 6. Streamlit User Interface
# -------------------------------------------------------------
st.title("🕵️ Live AI Fake News Validator")
st.markdown("Enter a topic below to fetch the latest breaking news. The underlying NLP model will evaluate the content's linguistic patterns to estimate credibility.")

topic = st.text_input("Enter a news topic (e.g., 'Economy', 'Technology', 'Elections'):")

# Securely retrieve the API key from Streamlit Cloud Secrets
try:
    API_KEY = st.secrets["NEWS_API_KEY"]
except KeyError:
    st.error("🚨 Configuration Error: 'NEWS_API_KEY' is missing from Streamlit Secrets.")
    st.stop()

# -------------------------------------------------------------
# 7. Execution Logic
# -------------------------------------------------------------
if st.button("Fetch & Analyze Live News", type="primary"):
    if topic:
        with st.spinner(f"Scraping the latest news for '{topic}'..."):
            
            # Fetch data from the web
            title, description, url = fetch_live_news(topic, API_KEY)
            
            if title and description:
                # Display the scraped article
                st.subheader("📰 Latest Headline")
                st.write(f"**{title}**")
                st.write(f"> *{description}*")
                if url:
                    st.caption(f"[Read full source article]({url})")
                
                # Push the live text through the AI Pipeline
                full_text = str(title) + " " + str(description)
                processed_text = clean_text(full_text)
                vectorized_input = vectorizer.transform([processed_text])
                prediction = model.predict(vectorized_input)[0]
                
                # Display the final verdict
                st.divider()
                st.subheader("🤖 AI Analysis Verdict:")
                if prediction == 1:
                    st.success("✅ **REAL NEWS** - The linguistic patterns closely match factual reporting standards.")
                else:
                    st.error("🚨 **FAKE NEWS DETECTED** - High probability of sensationalism, bias, or misinformation.")
            else:
                st.warning("Could not find recent news for this topic. Try broader keywords.")
    else:
        st.info("Please enter a topic to begin.")
